version: '3'

services:
  db:
    image: mariadb
    container_name: devbarber-db
    environment:
      - ALLOW_EMPTY_PASSOWORD=yes
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      # nossa porta exposta é a que vamos usar pra conectar via host, a porta interna é a que o laravel se conectará
      - ${DB_PORT_EXPOSE}:${DB_PORT} 
    volumes:
      - ./docker-compose/mysql/dump:/docker-entrypoint-initdb.d # dados iniciais
      - ./docker-compose/mysql/data:/var/lib/mysql # local dos dados do banco

  app:
    build: .
    image: apidevbarber # nossa imagem compilada
    container_name: devbarber-api
    restart: always
    volumes:
      - .:/var/www
    depends_on: 
      - db

  nginx:
    image: nginx:1.21.3-alpine
    container_name: devbarber-nginx
    ports:
      - ${APP_SERVER_PORT}:80
    volumes:
      - .:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    depends_on:
      - app
      

